package com.clarks.pojo;

import java.util.Date;

public class AdminUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_admin_user.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_admin_user.user_name
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_admin_user.password
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_admin_user.register_time
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_admin_user.last_login_time
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_admin_user.status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_admin_user.level
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_admin_user.mobile
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_admin_user.qq
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String qq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_admin_user.id
     *
     * @return the value of c_admin_user.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_admin_user.id
     *
     * @param id the value for c_admin_user.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_admin_user.user_name
     *
     * @return the value of c_admin_user.user_name
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_admin_user.user_name
     *
     * @param userName the value for c_admin_user.user_name
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_admin_user.password
     *
     * @return the value of c_admin_user.password
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_admin_user.password
     *
     * @param password the value for c_admin_user.password
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_admin_user.register_time
     *
     * @return the value of c_admin_user.register_time
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_admin_user.register_time
     *
     * @param registerTime the value for c_admin_user.register_time
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_admin_user.last_login_time
     *
     * @return the value of c_admin_user.last_login_time
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_admin_user.last_login_time
     *
     * @param lastLoginTime the value for c_admin_user.last_login_time
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_admin_user.status
     *
     * @return the value of c_admin_user.status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_admin_user.status
     *
     * @param status the value for c_admin_user.status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_admin_user.level
     *
     * @return the value of c_admin_user.level
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_admin_user.level
     *
     * @param level the value for c_admin_user.level
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_admin_user.mobile
     *
     * @return the value of c_admin_user.mobile
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_admin_user.mobile
     *
     * @param mobile the value for c_admin_user.mobile
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_admin_user.qq
     *
     * @return the value of c_admin_user.qq
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_admin_user.qq
     *
     * @param qq the value for c_admin_user.qq
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }
}