package com.clarks.pojo;

import java.util.ArrayList;
import java.util.List;

public class ConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public ConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNull() {
            addCriterion("project_name is null");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNotNull() {
            addCriterion("project_name is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNameEqualTo(String value) {
            addCriterion("project_name =", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotEqualTo(String value) {
            addCriterion("project_name <>", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThan(String value) {
            addCriterion("project_name >", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("project_name >=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThan(String value) {
            addCriterion("project_name <", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThanOrEqualTo(String value) {
            addCriterion("project_name <=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLike(String value) {
            addCriterion("project_name like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotLike(String value) {
            addCriterion("project_name not like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIn(List<String> values) {
            addCriterion("project_name in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotIn(List<String> values) {
            addCriterion("project_name not in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameBetween(String value1, String value2) {
            addCriterion("project_name between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotBetween(String value1, String value2) {
            addCriterion("project_name not between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andPortIsNull() {
            addCriterion("port is null");
            return (Criteria) this;
        }

        public Criteria andPortIsNotNull() {
            addCriterion("port is not null");
            return (Criteria) this;
        }

        public Criteria andPortEqualTo(String value) {
            addCriterion("port =", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotEqualTo(String value) {
            addCriterion("port <>", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThan(String value) {
            addCriterion("port >", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThanOrEqualTo(String value) {
            addCriterion("port >=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThan(String value) {
            addCriterion("port <", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThanOrEqualTo(String value) {
            addCriterion("port <=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLike(String value) {
            addCriterion("port like", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotLike(String value) {
            addCriterion("port not like", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortIn(List<String> values) {
            addCriterion("port in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotIn(List<String> values) {
            addCriterion("port not in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortBetween(String value1, String value2) {
            addCriterion("port between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotBetween(String value1, String value2) {
            addCriterion("port not between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andContextPathIsNull() {
            addCriterion("context_path is null");
            return (Criteria) this;
        }

        public Criteria andContextPathIsNotNull() {
            addCriterion("context_path is not null");
            return (Criteria) this;
        }

        public Criteria andContextPathEqualTo(String value) {
            addCriterion("context_path =", value, "contextPath");
            return (Criteria) this;
        }

        public Criteria andContextPathNotEqualTo(String value) {
            addCriterion("context_path <>", value, "contextPath");
            return (Criteria) this;
        }

        public Criteria andContextPathGreaterThan(String value) {
            addCriterion("context_path >", value, "contextPath");
            return (Criteria) this;
        }

        public Criteria andContextPathGreaterThanOrEqualTo(String value) {
            addCriterion("context_path >=", value, "contextPath");
            return (Criteria) this;
        }

        public Criteria andContextPathLessThan(String value) {
            addCriterion("context_path <", value, "contextPath");
            return (Criteria) this;
        }

        public Criteria andContextPathLessThanOrEqualTo(String value) {
            addCriterion("context_path <=", value, "contextPath");
            return (Criteria) this;
        }

        public Criteria andContextPathLike(String value) {
            addCriterion("context_path like", value, "contextPath");
            return (Criteria) this;
        }

        public Criteria andContextPathNotLike(String value) {
            addCriterion("context_path not like", value, "contextPath");
            return (Criteria) this;
        }

        public Criteria andContextPathIn(List<String> values) {
            addCriterion("context_path in", values, "contextPath");
            return (Criteria) this;
        }

        public Criteria andContextPathNotIn(List<String> values) {
            addCriterion("context_path not in", values, "contextPath");
            return (Criteria) this;
        }

        public Criteria andContextPathBetween(String value1, String value2) {
            addCriterion("context_path between", value1, value2, "contextPath");
            return (Criteria) this;
        }

        public Criteria andContextPathNotBetween(String value1, String value2) {
            addCriterion("context_path not between", value1, value2, "contextPath");
            return (Criteria) this;
        }

        public Criteria andFileDomainIsNull() {
            addCriterion("file_domain is null");
            return (Criteria) this;
        }

        public Criteria andFileDomainIsNotNull() {
            addCriterion("file_domain is not null");
            return (Criteria) this;
        }

        public Criteria andFileDomainEqualTo(String value) {
            addCriterion("file_domain =", value, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainNotEqualTo(String value) {
            addCriterion("file_domain <>", value, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainGreaterThan(String value) {
            addCriterion("file_domain >", value, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainGreaterThanOrEqualTo(String value) {
            addCriterion("file_domain >=", value, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainLessThan(String value) {
            addCriterion("file_domain <", value, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainLessThanOrEqualTo(String value) {
            addCriterion("file_domain <=", value, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainLike(String value) {
            addCriterion("file_domain like", value, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainNotLike(String value) {
            addCriterion("file_domain not like", value, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainIn(List<String> values) {
            addCriterion("file_domain in", values, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainNotIn(List<String> values) {
            addCriterion("file_domain not in", values, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainBetween(String value1, String value2) {
            addCriterion("file_domain between", value1, value2, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainNotBetween(String value1, String value2) {
            addCriterion("file_domain not between", value1, value2, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andRequestdomainIsNull() {
            addCriterion("requestDomain is null");
            return (Criteria) this;
        }

        public Criteria andRequestdomainIsNotNull() {
            addCriterion("requestDomain is not null");
            return (Criteria) this;
        }

        public Criteria andRequestdomainEqualTo(String value) {
            addCriterion("requestDomain =", value, "requestdomain");
            return (Criteria) this;
        }

        public Criteria andRequestdomainNotEqualTo(String value) {
            addCriterion("requestDomain <>", value, "requestdomain");
            return (Criteria) this;
        }

        public Criteria andRequestdomainGreaterThan(String value) {
            addCriterion("requestDomain >", value, "requestdomain");
            return (Criteria) this;
        }

        public Criteria andRequestdomainGreaterThanOrEqualTo(String value) {
            addCriterion("requestDomain >=", value, "requestdomain");
            return (Criteria) this;
        }

        public Criteria andRequestdomainLessThan(String value) {
            addCriterion("requestDomain <", value, "requestdomain");
            return (Criteria) this;
        }

        public Criteria andRequestdomainLessThanOrEqualTo(String value) {
            addCriterion("requestDomain <=", value, "requestdomain");
            return (Criteria) this;
        }

        public Criteria andRequestdomainLike(String value) {
            addCriterion("requestDomain like", value, "requestdomain");
            return (Criteria) this;
        }

        public Criteria andRequestdomainNotLike(String value) {
            addCriterion("requestDomain not like", value, "requestdomain");
            return (Criteria) this;
        }

        public Criteria andRequestdomainIn(List<String> values) {
            addCriterion("requestDomain in", values, "requestdomain");
            return (Criteria) this;
        }

        public Criteria andRequestdomainNotIn(List<String> values) {
            addCriterion("requestDomain not in", values, "requestdomain");
            return (Criteria) this;
        }

        public Criteria andRequestdomainBetween(String value1, String value2) {
            addCriterion("requestDomain between", value1, value2, "requestdomain");
            return (Criteria) this;
        }

        public Criteria andRequestdomainNotBetween(String value1, String value2) {
            addCriterion("requestDomain not between", value1, value2, "requestdomain");
            return (Criteria) this;
        }

        public Criteria andSecretPassIsNull() {
            addCriterion("secret_pass is null");
            return (Criteria) this;
        }

        public Criteria andSecretPassIsNotNull() {
            addCriterion("secret_pass is not null");
            return (Criteria) this;
        }

        public Criteria andSecretPassEqualTo(String value) {
            addCriterion("secret_pass =", value, "secretPass");
            return (Criteria) this;
        }

        public Criteria andSecretPassNotEqualTo(String value) {
            addCriterion("secret_pass <>", value, "secretPass");
            return (Criteria) this;
        }

        public Criteria andSecretPassGreaterThan(String value) {
            addCriterion("secret_pass >", value, "secretPass");
            return (Criteria) this;
        }

        public Criteria andSecretPassGreaterThanOrEqualTo(String value) {
            addCriterion("secret_pass >=", value, "secretPass");
            return (Criteria) this;
        }

        public Criteria andSecretPassLessThan(String value) {
            addCriterion("secret_pass <", value, "secretPass");
            return (Criteria) this;
        }

        public Criteria andSecretPassLessThanOrEqualTo(String value) {
            addCriterion("secret_pass <=", value, "secretPass");
            return (Criteria) this;
        }

        public Criteria andSecretPassLike(String value) {
            addCriterion("secret_pass like", value, "secretPass");
            return (Criteria) this;
        }

        public Criteria andSecretPassNotLike(String value) {
            addCriterion("secret_pass not like", value, "secretPass");
            return (Criteria) this;
        }

        public Criteria andSecretPassIn(List<String> values) {
            addCriterion("secret_pass in", values, "secretPass");
            return (Criteria) this;
        }

        public Criteria andSecretPassNotIn(List<String> values) {
            addCriterion("secret_pass not in", values, "secretPass");
            return (Criteria) this;
        }

        public Criteria andSecretPassBetween(String value1, String value2) {
            addCriterion("secret_pass between", value1, value2, "secretPass");
            return (Criteria) this;
        }

        public Criteria andSecretPassNotBetween(String value1, String value2) {
            addCriterion("secret_pass not between", value1, value2, "secretPass");
            return (Criteria) this;
        }

        public Criteria andSecretGetIsNull() {
            addCriterion("secret_get is null");
            return (Criteria) this;
        }

        public Criteria andSecretGetIsNotNull() {
            addCriterion("secret_get is not null");
            return (Criteria) this;
        }

        public Criteria andSecretGetEqualTo(String value) {
            addCriterion("secret_get =", value, "secretGet");
            return (Criteria) this;
        }

        public Criteria andSecretGetNotEqualTo(String value) {
            addCriterion("secret_get <>", value, "secretGet");
            return (Criteria) this;
        }

        public Criteria andSecretGetGreaterThan(String value) {
            addCriterion("secret_get >", value, "secretGet");
            return (Criteria) this;
        }

        public Criteria andSecretGetGreaterThanOrEqualTo(String value) {
            addCriterion("secret_get >=", value, "secretGet");
            return (Criteria) this;
        }

        public Criteria andSecretGetLessThan(String value) {
            addCriterion("secret_get <", value, "secretGet");
            return (Criteria) this;
        }

        public Criteria andSecretGetLessThanOrEqualTo(String value) {
            addCriterion("secret_get <=", value, "secretGet");
            return (Criteria) this;
        }

        public Criteria andSecretGetLike(String value) {
            addCriterion("secret_get like", value, "secretGet");
            return (Criteria) this;
        }

        public Criteria andSecretGetNotLike(String value) {
            addCriterion("secret_get not like", value, "secretGet");
            return (Criteria) this;
        }

        public Criteria andSecretGetIn(List<String> values) {
            addCriterion("secret_get in", values, "secretGet");
            return (Criteria) this;
        }

        public Criteria andSecretGetNotIn(List<String> values) {
            addCriterion("secret_get not in", values, "secretGet");
            return (Criteria) this;
        }

        public Criteria andSecretGetBetween(String value1, String value2) {
            addCriterion("secret_get between", value1, value2, "secretGet");
            return (Criteria) this;
        }

        public Criteria andSecretGetNotBetween(String value1, String value2) {
            addCriterion("secret_get not between", value1, value2, "secretGet");
            return (Criteria) this;
        }

        public Criteria andFirstLimitIsNull() {
            addCriterion("first_limit is null");
            return (Criteria) this;
        }

        public Criteria andFirstLimitIsNotNull() {
            addCriterion("first_limit is not null");
            return (Criteria) this;
        }

        public Criteria andFirstLimitEqualTo(Integer value) {
            addCriterion("first_limit =", value, "firstLimit");
            return (Criteria) this;
        }

        public Criteria andFirstLimitNotEqualTo(Integer value) {
            addCriterion("first_limit <>", value, "firstLimit");
            return (Criteria) this;
        }

        public Criteria andFirstLimitGreaterThan(Integer value) {
            addCriterion("first_limit >", value, "firstLimit");
            return (Criteria) this;
        }

        public Criteria andFirstLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("first_limit >=", value, "firstLimit");
            return (Criteria) this;
        }

        public Criteria andFirstLimitLessThan(Integer value) {
            addCriterion("first_limit <", value, "firstLimit");
            return (Criteria) this;
        }

        public Criteria andFirstLimitLessThanOrEqualTo(Integer value) {
            addCriterion("first_limit <=", value, "firstLimit");
            return (Criteria) this;
        }

        public Criteria andFirstLimitIn(List<Integer> values) {
            addCriterion("first_limit in", values, "firstLimit");
            return (Criteria) this;
        }

        public Criteria andFirstLimitNotIn(List<Integer> values) {
            addCriterion("first_limit not in", values, "firstLimit");
            return (Criteria) this;
        }

        public Criteria andFirstLimitBetween(Integer value1, Integer value2) {
            addCriterion("first_limit between", value1, value2, "firstLimit");
            return (Criteria) this;
        }

        public Criteria andFirstLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("first_limit not between", value1, value2, "firstLimit");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("app_id like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("app_id not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppSecretIsNull() {
            addCriterion("app_secret is null");
            return (Criteria) this;
        }

        public Criteria andAppSecretIsNotNull() {
            addCriterion("app_secret is not null");
            return (Criteria) this;
        }

        public Criteria andAppSecretEqualTo(String value) {
            addCriterion("app_secret =", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretNotEqualTo(String value) {
            addCriterion("app_secret <>", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretGreaterThan(String value) {
            addCriterion("app_secret >", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretGreaterThanOrEqualTo(String value) {
            addCriterion("app_secret >=", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretLessThan(String value) {
            addCriterion("app_secret <", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretLessThanOrEqualTo(String value) {
            addCriterion("app_secret <=", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretLike(String value) {
            addCriterion("app_secret like", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretNotLike(String value) {
            addCriterion("app_secret not like", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretIn(List<String> values) {
            addCriterion("app_secret in", values, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretNotIn(List<String> values) {
            addCriterion("app_secret not in", values, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretBetween(String value1, String value2) {
            addCriterion("app_secret between", value1, value2, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretNotBetween(String value1, String value2) {
            addCriterion("app_secret not between", value1, value2, "appSecret");
            return (Criteria) this;
        }

        public Criteria andPartnerkeyIsNull() {
            addCriterion("partnerkey is null");
            return (Criteria) this;
        }

        public Criteria andPartnerkeyIsNotNull() {
            addCriterion("partnerkey is not null");
            return (Criteria) this;
        }

        public Criteria andPartnerkeyEqualTo(String value) {
            addCriterion("partnerkey =", value, "partnerkey");
            return (Criteria) this;
        }

        public Criteria andPartnerkeyNotEqualTo(String value) {
            addCriterion("partnerkey <>", value, "partnerkey");
            return (Criteria) this;
        }

        public Criteria andPartnerkeyGreaterThan(String value) {
            addCriterion("partnerkey >", value, "partnerkey");
            return (Criteria) this;
        }

        public Criteria andPartnerkeyGreaterThanOrEqualTo(String value) {
            addCriterion("partnerkey >=", value, "partnerkey");
            return (Criteria) this;
        }

        public Criteria andPartnerkeyLessThan(String value) {
            addCriterion("partnerkey <", value, "partnerkey");
            return (Criteria) this;
        }

        public Criteria andPartnerkeyLessThanOrEqualTo(String value) {
            addCriterion("partnerkey <=", value, "partnerkey");
            return (Criteria) this;
        }

        public Criteria andPartnerkeyLike(String value) {
            addCriterion("partnerkey like", value, "partnerkey");
            return (Criteria) this;
        }

        public Criteria andPartnerkeyNotLike(String value) {
            addCriterion("partnerkey not like", value, "partnerkey");
            return (Criteria) this;
        }

        public Criteria andPartnerkeyIn(List<String> values) {
            addCriterion("partnerkey in", values, "partnerkey");
            return (Criteria) this;
        }

        public Criteria andPartnerkeyNotIn(List<String> values) {
            addCriterion("partnerkey not in", values, "partnerkey");
            return (Criteria) this;
        }

        public Criteria andPartnerkeyBetween(String value1, String value2) {
            addCriterion("partnerkey between", value1, value2, "partnerkey");
            return (Criteria) this;
        }

        public Criteria andPartnerkeyNotBetween(String value1, String value2) {
            addCriterion("partnerkey not between", value1, value2, "partnerkey");
            return (Criteria) this;
        }

        public Criteria andShareTitleIsNull() {
            addCriterion("share_title is null");
            return (Criteria) this;
        }

        public Criteria andShareTitleIsNotNull() {
            addCriterion("share_title is not null");
            return (Criteria) this;
        }

        public Criteria andShareTitleEqualTo(String value) {
            addCriterion("share_title =", value, "shareTitle");
            return (Criteria) this;
        }

        public Criteria andShareTitleNotEqualTo(String value) {
            addCriterion("share_title <>", value, "shareTitle");
            return (Criteria) this;
        }

        public Criteria andShareTitleGreaterThan(String value) {
            addCriterion("share_title >", value, "shareTitle");
            return (Criteria) this;
        }

        public Criteria andShareTitleGreaterThanOrEqualTo(String value) {
            addCriterion("share_title >=", value, "shareTitle");
            return (Criteria) this;
        }

        public Criteria andShareTitleLessThan(String value) {
            addCriterion("share_title <", value, "shareTitle");
            return (Criteria) this;
        }

        public Criteria andShareTitleLessThanOrEqualTo(String value) {
            addCriterion("share_title <=", value, "shareTitle");
            return (Criteria) this;
        }

        public Criteria andShareTitleLike(String value) {
            addCriterion("share_title like", value, "shareTitle");
            return (Criteria) this;
        }

        public Criteria andShareTitleNotLike(String value) {
            addCriterion("share_title not like", value, "shareTitle");
            return (Criteria) this;
        }

        public Criteria andShareTitleIn(List<String> values) {
            addCriterion("share_title in", values, "shareTitle");
            return (Criteria) this;
        }

        public Criteria andShareTitleNotIn(List<String> values) {
            addCriterion("share_title not in", values, "shareTitle");
            return (Criteria) this;
        }

        public Criteria andShareTitleBetween(String value1, String value2) {
            addCriterion("share_title between", value1, value2, "shareTitle");
            return (Criteria) this;
        }

        public Criteria andShareTitleNotBetween(String value1, String value2) {
            addCriterion("share_title not between", value1, value2, "shareTitle");
            return (Criteria) this;
        }

        public Criteria andShareLinkIsNull() {
            addCriterion("share_link is null");
            return (Criteria) this;
        }

        public Criteria andShareLinkIsNotNull() {
            addCriterion("share_link is not null");
            return (Criteria) this;
        }

        public Criteria andShareLinkEqualTo(String value) {
            addCriterion("share_link =", value, "shareLink");
            return (Criteria) this;
        }

        public Criteria andShareLinkNotEqualTo(String value) {
            addCriterion("share_link <>", value, "shareLink");
            return (Criteria) this;
        }

        public Criteria andShareLinkGreaterThan(String value) {
            addCriterion("share_link >", value, "shareLink");
            return (Criteria) this;
        }

        public Criteria andShareLinkGreaterThanOrEqualTo(String value) {
            addCriterion("share_link >=", value, "shareLink");
            return (Criteria) this;
        }

        public Criteria andShareLinkLessThan(String value) {
            addCriterion("share_link <", value, "shareLink");
            return (Criteria) this;
        }

        public Criteria andShareLinkLessThanOrEqualTo(String value) {
            addCriterion("share_link <=", value, "shareLink");
            return (Criteria) this;
        }

        public Criteria andShareLinkLike(String value) {
            addCriterion("share_link like", value, "shareLink");
            return (Criteria) this;
        }

        public Criteria andShareLinkNotLike(String value) {
            addCriterion("share_link not like", value, "shareLink");
            return (Criteria) this;
        }

        public Criteria andShareLinkIn(List<String> values) {
            addCriterion("share_link in", values, "shareLink");
            return (Criteria) this;
        }

        public Criteria andShareLinkNotIn(List<String> values) {
            addCriterion("share_link not in", values, "shareLink");
            return (Criteria) this;
        }

        public Criteria andShareLinkBetween(String value1, String value2) {
            addCriterion("share_link between", value1, value2, "shareLink");
            return (Criteria) this;
        }

        public Criteria andShareLinkNotBetween(String value1, String value2) {
            addCriterion("share_link not between", value1, value2, "shareLink");
            return (Criteria) this;
        }

        public Criteria andShareDescIsNull() {
            addCriterion("share_desc is null");
            return (Criteria) this;
        }

        public Criteria andShareDescIsNotNull() {
            addCriterion("share_desc is not null");
            return (Criteria) this;
        }

        public Criteria andShareDescEqualTo(String value) {
            addCriterion("share_desc =", value, "shareDesc");
            return (Criteria) this;
        }

        public Criteria andShareDescNotEqualTo(String value) {
            addCriterion("share_desc <>", value, "shareDesc");
            return (Criteria) this;
        }

        public Criteria andShareDescGreaterThan(String value) {
            addCriterion("share_desc >", value, "shareDesc");
            return (Criteria) this;
        }

        public Criteria andShareDescGreaterThanOrEqualTo(String value) {
            addCriterion("share_desc >=", value, "shareDesc");
            return (Criteria) this;
        }

        public Criteria andShareDescLessThan(String value) {
            addCriterion("share_desc <", value, "shareDesc");
            return (Criteria) this;
        }

        public Criteria andShareDescLessThanOrEqualTo(String value) {
            addCriterion("share_desc <=", value, "shareDesc");
            return (Criteria) this;
        }

        public Criteria andShareDescLike(String value) {
            addCriterion("share_desc like", value, "shareDesc");
            return (Criteria) this;
        }

        public Criteria andShareDescNotLike(String value) {
            addCriterion("share_desc not like", value, "shareDesc");
            return (Criteria) this;
        }

        public Criteria andShareDescIn(List<String> values) {
            addCriterion("share_desc in", values, "shareDesc");
            return (Criteria) this;
        }

        public Criteria andShareDescNotIn(List<String> values) {
            addCriterion("share_desc not in", values, "shareDesc");
            return (Criteria) this;
        }

        public Criteria andShareDescBetween(String value1, String value2) {
            addCriterion("share_desc between", value1, value2, "shareDesc");
            return (Criteria) this;
        }

        public Criteria andShareDescNotBetween(String value1, String value2) {
            addCriterion("share_desc not between", value1, value2, "shareDesc");
            return (Criteria) this;
        }

        public Criteria andShareImgIsNull() {
            addCriterion("share_img is null");
            return (Criteria) this;
        }

        public Criteria andShareImgIsNotNull() {
            addCriterion("share_img is not null");
            return (Criteria) this;
        }

        public Criteria andShareImgEqualTo(String value) {
            addCriterion("share_img =", value, "shareImg");
            return (Criteria) this;
        }

        public Criteria andShareImgNotEqualTo(String value) {
            addCriterion("share_img <>", value, "shareImg");
            return (Criteria) this;
        }

        public Criteria andShareImgGreaterThan(String value) {
            addCriterion("share_img >", value, "shareImg");
            return (Criteria) this;
        }

        public Criteria andShareImgGreaterThanOrEqualTo(String value) {
            addCriterion("share_img >=", value, "shareImg");
            return (Criteria) this;
        }

        public Criteria andShareImgLessThan(String value) {
            addCriterion("share_img <", value, "shareImg");
            return (Criteria) this;
        }

        public Criteria andShareImgLessThanOrEqualTo(String value) {
            addCriterion("share_img <=", value, "shareImg");
            return (Criteria) this;
        }

        public Criteria andShareImgLike(String value) {
            addCriterion("share_img like", value, "shareImg");
            return (Criteria) this;
        }

        public Criteria andShareImgNotLike(String value) {
            addCriterion("share_img not like", value, "shareImg");
            return (Criteria) this;
        }

        public Criteria andShareImgIn(List<String> values) {
            addCriterion("share_img in", values, "shareImg");
            return (Criteria) this;
        }

        public Criteria andShareImgNotIn(List<String> values) {
            addCriterion("share_img not in", values, "shareImg");
            return (Criteria) this;
        }

        public Criteria andShareImgBetween(String value1, String value2) {
            addCriterion("share_img between", value1, value2, "shareImg");
            return (Criteria) this;
        }

        public Criteria andShareImgNotBetween(String value1, String value2) {
            addCriterion("share_img not between", value1, value2, "shareImg");
            return (Criteria) this;
        }

        public Criteria andShareTypeIsNull() {
            addCriterion("share_type is null");
            return (Criteria) this;
        }

        public Criteria andShareTypeIsNotNull() {
            addCriterion("share_type is not null");
            return (Criteria) this;
        }

        public Criteria andShareTypeEqualTo(String value) {
            addCriterion("share_type =", value, "shareType");
            return (Criteria) this;
        }

        public Criteria andShareTypeNotEqualTo(String value) {
            addCriterion("share_type <>", value, "shareType");
            return (Criteria) this;
        }

        public Criteria andShareTypeGreaterThan(String value) {
            addCriterion("share_type >", value, "shareType");
            return (Criteria) this;
        }

        public Criteria andShareTypeGreaterThanOrEqualTo(String value) {
            addCriterion("share_type >=", value, "shareType");
            return (Criteria) this;
        }

        public Criteria andShareTypeLessThan(String value) {
            addCriterion("share_type <", value, "shareType");
            return (Criteria) this;
        }

        public Criteria andShareTypeLessThanOrEqualTo(String value) {
            addCriterion("share_type <=", value, "shareType");
            return (Criteria) this;
        }

        public Criteria andShareTypeLike(String value) {
            addCriterion("share_type like", value, "shareType");
            return (Criteria) this;
        }

        public Criteria andShareTypeNotLike(String value) {
            addCriterion("share_type not like", value, "shareType");
            return (Criteria) this;
        }

        public Criteria andShareTypeIn(List<String> values) {
            addCriterion("share_type in", values, "shareType");
            return (Criteria) this;
        }

        public Criteria andShareTypeNotIn(List<String> values) {
            addCriterion("share_type not in", values, "shareType");
            return (Criteria) this;
        }

        public Criteria andShareTypeBetween(String value1, String value2) {
            addCriterion("share_type between", value1, value2, "shareType");
            return (Criteria) this;
        }

        public Criteria andShareTypeNotBetween(String value1, String value2) {
            addCriterion("share_type not between", value1, value2, "shareType");
            return (Criteria) this;
        }

        public Criteria andShareDataUrlIsNull() {
            addCriterion("share_data_url is null");
            return (Criteria) this;
        }

        public Criteria andShareDataUrlIsNotNull() {
            addCriterion("share_data_url is not null");
            return (Criteria) this;
        }

        public Criteria andShareDataUrlEqualTo(String value) {
            addCriterion("share_data_url =", value, "shareDataUrl");
            return (Criteria) this;
        }

        public Criteria andShareDataUrlNotEqualTo(String value) {
            addCriterion("share_data_url <>", value, "shareDataUrl");
            return (Criteria) this;
        }

        public Criteria andShareDataUrlGreaterThan(String value) {
            addCriterion("share_data_url >", value, "shareDataUrl");
            return (Criteria) this;
        }

        public Criteria andShareDataUrlGreaterThanOrEqualTo(String value) {
            addCriterion("share_data_url >=", value, "shareDataUrl");
            return (Criteria) this;
        }

        public Criteria andShareDataUrlLessThan(String value) {
            addCriterion("share_data_url <", value, "shareDataUrl");
            return (Criteria) this;
        }

        public Criteria andShareDataUrlLessThanOrEqualTo(String value) {
            addCriterion("share_data_url <=", value, "shareDataUrl");
            return (Criteria) this;
        }

        public Criteria andShareDataUrlLike(String value) {
            addCriterion("share_data_url like", value, "shareDataUrl");
            return (Criteria) this;
        }

        public Criteria andShareDataUrlNotLike(String value) {
            addCriterion("share_data_url not like", value, "shareDataUrl");
            return (Criteria) this;
        }

        public Criteria andShareDataUrlIn(List<String> values) {
            addCriterion("share_data_url in", values, "shareDataUrl");
            return (Criteria) this;
        }

        public Criteria andShareDataUrlNotIn(List<String> values) {
            addCriterion("share_data_url not in", values, "shareDataUrl");
            return (Criteria) this;
        }

        public Criteria andShareDataUrlBetween(String value1, String value2) {
            addCriterion("share_data_url between", value1, value2, "shareDataUrl");
            return (Criteria) this;
        }

        public Criteria andShareDataUrlNotBetween(String value1, String value2) {
            addCriterion("share_data_url not between", value1, value2, "shareDataUrl");
            return (Criteria) this;
        }

        public Criteria andTestOpenIdApiIsNull() {
            addCriterion("test_open_id_api is null");
            return (Criteria) this;
        }

        public Criteria andTestOpenIdApiIsNotNull() {
            addCriterion("test_open_id_api is not null");
            return (Criteria) this;
        }

        public Criteria andTestOpenIdApiEqualTo(String value) {
            addCriterion("test_open_id_api =", value, "testOpenIdApi");
            return (Criteria) this;
        }

        public Criteria andTestOpenIdApiNotEqualTo(String value) {
            addCriterion("test_open_id_api <>", value, "testOpenIdApi");
            return (Criteria) this;
        }

        public Criteria andTestOpenIdApiGreaterThan(String value) {
            addCriterion("test_open_id_api >", value, "testOpenIdApi");
            return (Criteria) this;
        }

        public Criteria andTestOpenIdApiGreaterThanOrEqualTo(String value) {
            addCriterion("test_open_id_api >=", value, "testOpenIdApi");
            return (Criteria) this;
        }

        public Criteria andTestOpenIdApiLessThan(String value) {
            addCriterion("test_open_id_api <", value, "testOpenIdApi");
            return (Criteria) this;
        }

        public Criteria andTestOpenIdApiLessThanOrEqualTo(String value) {
            addCriterion("test_open_id_api <=", value, "testOpenIdApi");
            return (Criteria) this;
        }

        public Criteria andTestOpenIdApiLike(String value) {
            addCriterion("test_open_id_api like", value, "testOpenIdApi");
            return (Criteria) this;
        }

        public Criteria andTestOpenIdApiNotLike(String value) {
            addCriterion("test_open_id_api not like", value, "testOpenIdApi");
            return (Criteria) this;
        }

        public Criteria andTestOpenIdApiIn(List<String> values) {
            addCriterion("test_open_id_api in", values, "testOpenIdApi");
            return (Criteria) this;
        }

        public Criteria andTestOpenIdApiNotIn(List<String> values) {
            addCriterion("test_open_id_api not in", values, "testOpenIdApi");
            return (Criteria) this;
        }

        public Criteria andTestOpenIdApiBetween(String value1, String value2) {
            addCriterion("test_open_id_api between", value1, value2, "testOpenIdApi");
            return (Criteria) this;
        }

        public Criteria andTestOpenIdApiNotBetween(String value1, String value2) {
            addCriterion("test_open_id_api not between", value1, value2, "testOpenIdApi");
            return (Criteria) this;
        }

        public Criteria andSignatureApiIsNull() {
            addCriterion("signature_api is null");
            return (Criteria) this;
        }

        public Criteria andSignatureApiIsNotNull() {
            addCriterion("signature_api is not null");
            return (Criteria) this;
        }

        public Criteria andSignatureApiEqualTo(String value) {
            addCriterion("signature_api =", value, "signatureApi");
            return (Criteria) this;
        }

        public Criteria andSignatureApiNotEqualTo(String value) {
            addCriterion("signature_api <>", value, "signatureApi");
            return (Criteria) this;
        }

        public Criteria andSignatureApiGreaterThan(String value) {
            addCriterion("signature_api >", value, "signatureApi");
            return (Criteria) this;
        }

        public Criteria andSignatureApiGreaterThanOrEqualTo(String value) {
            addCriterion("signature_api >=", value, "signatureApi");
            return (Criteria) this;
        }

        public Criteria andSignatureApiLessThan(String value) {
            addCriterion("signature_api <", value, "signatureApi");
            return (Criteria) this;
        }

        public Criteria andSignatureApiLessThanOrEqualTo(String value) {
            addCriterion("signature_api <=", value, "signatureApi");
            return (Criteria) this;
        }

        public Criteria andSignatureApiLike(String value) {
            addCriterion("signature_api like", value, "signatureApi");
            return (Criteria) this;
        }

        public Criteria andSignatureApiNotLike(String value) {
            addCriterion("signature_api not like", value, "signatureApi");
            return (Criteria) this;
        }

        public Criteria andSignatureApiIn(List<String> values) {
            addCriterion("signature_api in", values, "signatureApi");
            return (Criteria) this;
        }

        public Criteria andSignatureApiNotIn(List<String> values) {
            addCriterion("signature_api not in", values, "signatureApi");
            return (Criteria) this;
        }

        public Criteria andSignatureApiBetween(String value1, String value2) {
            addCriterion("signature_api between", value1, value2, "signatureApi");
            return (Criteria) this;
        }

        public Criteria andSignatureApiNotBetween(String value1, String value2) {
            addCriterion("signature_api not between", value1, value2, "signatureApi");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_config
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 14 15:34:55 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}