package com.clarks.pojo;

import java.util.Date;

public class DailyCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_daily_count.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_daily_count.page_url
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String pageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_daily_count.nick_name
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_daily_count.user_ip
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String userIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_daily_count.login_time
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_daily_count.user_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_daily_count.id
     *
     * @return the value of c_daily_count.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_daily_count.id
     *
     * @param id the value for c_daily_count.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_daily_count.page_url
     *
     * @return the value of c_daily_count.page_url
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getPageUrl() {
        return pageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_daily_count.page_url
     *
     * @param pageUrl the value for c_daily_count.page_url
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl == null ? null : pageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_daily_count.nick_name
     *
     * @return the value of c_daily_count.nick_name
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_daily_count.nick_name
     *
     * @param nickName the value for c_daily_count.nick_name
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_daily_count.user_ip
     *
     * @return the value of c_daily_count.user_ip
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getUserIp() {
        return userIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_daily_count.user_ip
     *
     * @param userIp the value for c_daily_count.user_ip
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setUserIp(String userIp) {
        this.userIp = userIp == null ? null : userIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_daily_count.login_time
     *
     * @return the value of c_daily_count.login_time
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_daily_count.login_time
     *
     * @param loginTime the value for c_daily_count.login_time
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_daily_count.user_id
     *
     * @return the value of c_daily_count.user_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_daily_count.user_id
     *
     * @param userId the value for c_daily_count.user_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}