package com.clarks.pojo;

import java.util.Date;

public class File {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_front_file.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_front_file.img_url
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_front_file.mv_url
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String mvUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_front_file.img_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Date imgDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_front_file.mv_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Date mvDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_front_file.id
     *
     * @return the value of c_front_file.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_front_file.id
     *
     * @param id the value for c_front_file.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_front_file.img_url
     *
     * @return the value of c_front_file.img_url
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_front_file.img_url
     *
     * @param imgUrl the value for c_front_file.img_url
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_front_file.mv_url
     *
     * @return the value of c_front_file.mv_url
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getMvUrl() {
        return mvUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_front_file.mv_url
     *
     * @param mvUrl the value for c_front_file.mv_url
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setMvUrl(String mvUrl) {
        this.mvUrl = mvUrl == null ? null : mvUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_front_file.img_date
     *
     * @return the value of c_front_file.img_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Date getImgDate() {
        return imgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_front_file.img_date
     *
     * @param imgDate the value for c_front_file.img_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setImgDate(Date imgDate) {
        this.imgDate = imgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_front_file.mv_date
     *
     * @return the value of c_front_file.mv_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Date getMvDate() {
        return mvDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_front_file.mv_date
     *
     * @param mvDate the value for c_front_file.mv_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setMvDate(Date mvDate) {
        this.mvDate = mvDate;
    }
}