package com.clarks.pojo;

import java.util.ArrayList;
import java.util.List;

public class GameStatusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public GameStatusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andFirstPassIsNull() {
            addCriterion("first_pass is null");
            return (Criteria) this;
        }

        public Criteria andFirstPassIsNotNull() {
            addCriterion("first_pass is not null");
            return (Criteria) this;
        }

        public Criteria andFirstPassEqualTo(Integer value) {
            addCriterion("first_pass =", value, "firstPass");
            return (Criteria) this;
        }

        public Criteria andFirstPassNotEqualTo(Integer value) {
            addCriterion("first_pass <>", value, "firstPass");
            return (Criteria) this;
        }

        public Criteria andFirstPassGreaterThan(Integer value) {
            addCriterion("first_pass >", value, "firstPass");
            return (Criteria) this;
        }

        public Criteria andFirstPassGreaterThanOrEqualTo(Integer value) {
            addCriterion("first_pass >=", value, "firstPass");
            return (Criteria) this;
        }

        public Criteria andFirstPassLessThan(Integer value) {
            addCriterion("first_pass <", value, "firstPass");
            return (Criteria) this;
        }

        public Criteria andFirstPassLessThanOrEqualTo(Integer value) {
            addCriterion("first_pass <=", value, "firstPass");
            return (Criteria) this;
        }

        public Criteria andFirstPassIn(List<Integer> values) {
            addCriterion("first_pass in", values, "firstPass");
            return (Criteria) this;
        }

        public Criteria andFirstPassNotIn(List<Integer> values) {
            addCriterion("first_pass not in", values, "firstPass");
            return (Criteria) this;
        }

        public Criteria andFirstPassBetween(Integer value1, Integer value2) {
            addCriterion("first_pass between", value1, value2, "firstPass");
            return (Criteria) this;
        }

        public Criteria andFirstPassNotBetween(Integer value1, Integer value2) {
            addCriterion("first_pass not between", value1, value2, "firstPass");
            return (Criteria) this;
        }

        public Criteria andFirstJoinIsNull() {
            addCriterion("first_join is null");
            return (Criteria) this;
        }

        public Criteria andFirstJoinIsNotNull() {
            addCriterion("first_join is not null");
            return (Criteria) this;
        }

        public Criteria andFirstJoinEqualTo(Integer value) {
            addCriterion("first_join =", value, "firstJoin");
            return (Criteria) this;
        }

        public Criteria andFirstJoinNotEqualTo(Integer value) {
            addCriterion("first_join <>", value, "firstJoin");
            return (Criteria) this;
        }

        public Criteria andFirstJoinGreaterThan(Integer value) {
            addCriterion("first_join >", value, "firstJoin");
            return (Criteria) this;
        }

        public Criteria andFirstJoinGreaterThanOrEqualTo(Integer value) {
            addCriterion("first_join >=", value, "firstJoin");
            return (Criteria) this;
        }

        public Criteria andFirstJoinLessThan(Integer value) {
            addCriterion("first_join <", value, "firstJoin");
            return (Criteria) this;
        }

        public Criteria andFirstJoinLessThanOrEqualTo(Integer value) {
            addCriterion("first_join <=", value, "firstJoin");
            return (Criteria) this;
        }

        public Criteria andFirstJoinIn(List<Integer> values) {
            addCriterion("first_join in", values, "firstJoin");
            return (Criteria) this;
        }

        public Criteria andFirstJoinNotIn(List<Integer> values) {
            addCriterion("first_join not in", values, "firstJoin");
            return (Criteria) this;
        }

        public Criteria andFirstJoinBetween(Integer value1, Integer value2) {
            addCriterion("first_join between", value1, value2, "firstJoin");
            return (Criteria) this;
        }

        public Criteria andFirstJoinNotBetween(Integer value1, Integer value2) {
            addCriterion("first_join not between", value1, value2, "firstJoin");
            return (Criteria) this;
        }

        public Criteria andSecondJoinIsNull() {
            addCriterion("second_join is null");
            return (Criteria) this;
        }

        public Criteria andSecondJoinIsNotNull() {
            addCriterion("second_join is not null");
            return (Criteria) this;
        }

        public Criteria andSecondJoinEqualTo(Integer value) {
            addCriterion("second_join =", value, "secondJoin");
            return (Criteria) this;
        }

        public Criteria andSecondJoinNotEqualTo(Integer value) {
            addCriterion("second_join <>", value, "secondJoin");
            return (Criteria) this;
        }

        public Criteria andSecondJoinGreaterThan(Integer value) {
            addCriterion("second_join >", value, "secondJoin");
            return (Criteria) this;
        }

        public Criteria andSecondJoinGreaterThanOrEqualTo(Integer value) {
            addCriterion("second_join >=", value, "secondJoin");
            return (Criteria) this;
        }

        public Criteria andSecondJoinLessThan(Integer value) {
            addCriterion("second_join <", value, "secondJoin");
            return (Criteria) this;
        }

        public Criteria andSecondJoinLessThanOrEqualTo(Integer value) {
            addCriterion("second_join <=", value, "secondJoin");
            return (Criteria) this;
        }

        public Criteria andSecondJoinIn(List<Integer> values) {
            addCriterion("second_join in", values, "secondJoin");
            return (Criteria) this;
        }

        public Criteria andSecondJoinNotIn(List<Integer> values) {
            addCriterion("second_join not in", values, "secondJoin");
            return (Criteria) this;
        }

        public Criteria andSecondJoinBetween(Integer value1, Integer value2) {
            addCriterion("second_join between", value1, value2, "secondJoin");
            return (Criteria) this;
        }

        public Criteria andSecondJoinNotBetween(Integer value1, Integer value2) {
            addCriterion("second_join not between", value1, value2, "secondJoin");
            return (Criteria) this;
        }

        public Criteria andFirstBestIsNull() {
            addCriterion("first_best is null");
            return (Criteria) this;
        }

        public Criteria andFirstBestIsNotNull() {
            addCriterion("first_best is not null");
            return (Criteria) this;
        }

        public Criteria andFirstBestEqualTo(Integer value) {
            addCriterion("first_best =", value, "firstBest");
            return (Criteria) this;
        }

        public Criteria andFirstBestNotEqualTo(Integer value) {
            addCriterion("first_best <>", value, "firstBest");
            return (Criteria) this;
        }

        public Criteria andFirstBestGreaterThan(Integer value) {
            addCriterion("first_best >", value, "firstBest");
            return (Criteria) this;
        }

        public Criteria andFirstBestGreaterThanOrEqualTo(Integer value) {
            addCriterion("first_best >=", value, "firstBest");
            return (Criteria) this;
        }

        public Criteria andFirstBestLessThan(Integer value) {
            addCriterion("first_best <", value, "firstBest");
            return (Criteria) this;
        }

        public Criteria andFirstBestLessThanOrEqualTo(Integer value) {
            addCriterion("first_best <=", value, "firstBest");
            return (Criteria) this;
        }

        public Criteria andFirstBestIn(List<Integer> values) {
            addCriterion("first_best in", values, "firstBest");
            return (Criteria) this;
        }

        public Criteria andFirstBestNotIn(List<Integer> values) {
            addCriterion("first_best not in", values, "firstBest");
            return (Criteria) this;
        }

        public Criteria andFirstBestBetween(Integer value1, Integer value2) {
            addCriterion("first_best between", value1, value2, "firstBest");
            return (Criteria) this;
        }

        public Criteria andFirstBestNotBetween(Integer value1, Integer value2) {
            addCriterion("first_best not between", value1, value2, "firstBest");
            return (Criteria) this;
        }

        public Criteria andSecondPassIsNull() {
            addCriterion("second_pass is null");
            return (Criteria) this;
        }

        public Criteria andSecondPassIsNotNull() {
            addCriterion("second_pass is not null");
            return (Criteria) this;
        }

        public Criteria andSecondPassEqualTo(Integer value) {
            addCriterion("second_pass =", value, "secondPass");
            return (Criteria) this;
        }

        public Criteria andSecondPassNotEqualTo(Integer value) {
            addCriterion("second_pass <>", value, "secondPass");
            return (Criteria) this;
        }

        public Criteria andSecondPassGreaterThan(Integer value) {
            addCriterion("second_pass >", value, "secondPass");
            return (Criteria) this;
        }

        public Criteria andSecondPassGreaterThanOrEqualTo(Integer value) {
            addCriterion("second_pass >=", value, "secondPass");
            return (Criteria) this;
        }

        public Criteria andSecondPassLessThan(Integer value) {
            addCriterion("second_pass <", value, "secondPass");
            return (Criteria) this;
        }

        public Criteria andSecondPassLessThanOrEqualTo(Integer value) {
            addCriterion("second_pass <=", value, "secondPass");
            return (Criteria) this;
        }

        public Criteria andSecondPassIn(List<Integer> values) {
            addCriterion("second_pass in", values, "secondPass");
            return (Criteria) this;
        }

        public Criteria andSecondPassNotIn(List<Integer> values) {
            addCriterion("second_pass not in", values, "secondPass");
            return (Criteria) this;
        }

        public Criteria andSecondPassBetween(Integer value1, Integer value2) {
            addCriterion("second_pass between", value1, value2, "secondPass");
            return (Criteria) this;
        }

        public Criteria andSecondPassNotBetween(Integer value1, Integer value2) {
            addCriterion("second_pass not between", value1, value2, "secondPass");
            return (Criteria) this;
        }

        public Criteria andSecondBestIsNull() {
            addCriterion("second_best is null");
            return (Criteria) this;
        }

        public Criteria andSecondBestIsNotNull() {
            addCriterion("second_best is not null");
            return (Criteria) this;
        }

        public Criteria andSecondBestEqualTo(Integer value) {
            addCriterion("second_best =", value, "secondBest");
            return (Criteria) this;
        }

        public Criteria andSecondBestNotEqualTo(Integer value) {
            addCriterion("second_best <>", value, "secondBest");
            return (Criteria) this;
        }

        public Criteria andSecondBestGreaterThan(Integer value) {
            addCriterion("second_best >", value, "secondBest");
            return (Criteria) this;
        }

        public Criteria andSecondBestGreaterThanOrEqualTo(Integer value) {
            addCriterion("second_best >=", value, "secondBest");
            return (Criteria) this;
        }

        public Criteria andSecondBestLessThan(Integer value) {
            addCriterion("second_best <", value, "secondBest");
            return (Criteria) this;
        }

        public Criteria andSecondBestLessThanOrEqualTo(Integer value) {
            addCriterion("second_best <=", value, "secondBest");
            return (Criteria) this;
        }

        public Criteria andSecondBestIn(List<Integer> values) {
            addCriterion("second_best in", values, "secondBest");
            return (Criteria) this;
        }

        public Criteria andSecondBestNotIn(List<Integer> values) {
            addCriterion("second_best not in", values, "secondBest");
            return (Criteria) this;
        }

        public Criteria andSecondBestBetween(Integer value1, Integer value2) {
            addCriterion("second_best between", value1, value2, "secondBest");
            return (Criteria) this;
        }

        public Criteria andSecondBestNotBetween(Integer value1, Integer value2) {
            addCriterion("second_best not between", value1, value2, "secondBest");
            return (Criteria) this;
        }

        public Criteria andIsScanIsNull() {
            addCriterion("is_scan is null");
            return (Criteria) this;
        }

        public Criteria andIsScanIsNotNull() {
            addCriterion("is_scan is not null");
            return (Criteria) this;
        }

        public Criteria andIsScanEqualTo(Integer value) {
            addCriterion("is_scan =", value, "isScan");
            return (Criteria) this;
        }

        public Criteria andIsScanNotEqualTo(Integer value) {
            addCriterion("is_scan <>", value, "isScan");
            return (Criteria) this;
        }

        public Criteria andIsScanGreaterThan(Integer value) {
            addCriterion("is_scan >", value, "isScan");
            return (Criteria) this;
        }

        public Criteria andIsScanGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_scan >=", value, "isScan");
            return (Criteria) this;
        }

        public Criteria andIsScanLessThan(Integer value) {
            addCriterion("is_scan <", value, "isScan");
            return (Criteria) this;
        }

        public Criteria andIsScanLessThanOrEqualTo(Integer value) {
            addCriterion("is_scan <=", value, "isScan");
            return (Criteria) this;
        }

        public Criteria andIsScanIn(List<Integer> values) {
            addCriterion("is_scan in", values, "isScan");
            return (Criteria) this;
        }

        public Criteria andIsScanNotIn(List<Integer> values) {
            addCriterion("is_scan not in", values, "isScan");
            return (Criteria) this;
        }

        public Criteria andIsScanBetween(Integer value1, Integer value2) {
            addCriterion("is_scan between", value1, value2, "isScan");
            return (Criteria) this;
        }

        public Criteria andIsScanNotBetween(Integer value1, Integer value2) {
            addCriterion("is_scan not between", value1, value2, "isScan");
            return (Criteria) this;
        }

        public Criteria andIsDrawIsNull() {
            addCriterion("is_draw is null");
            return (Criteria) this;
        }

        public Criteria andIsDrawIsNotNull() {
            addCriterion("is_draw is not null");
            return (Criteria) this;
        }

        public Criteria andIsDrawEqualTo(Integer value) {
            addCriterion("is_draw =", value, "isDraw");
            return (Criteria) this;
        }

        public Criteria andIsDrawNotEqualTo(Integer value) {
            addCriterion("is_draw <>", value, "isDraw");
            return (Criteria) this;
        }

        public Criteria andIsDrawGreaterThan(Integer value) {
            addCriterion("is_draw >", value, "isDraw");
            return (Criteria) this;
        }

        public Criteria andIsDrawGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_draw >=", value, "isDraw");
            return (Criteria) this;
        }

        public Criteria andIsDrawLessThan(Integer value) {
            addCriterion("is_draw <", value, "isDraw");
            return (Criteria) this;
        }

        public Criteria andIsDrawLessThanOrEqualTo(Integer value) {
            addCriterion("is_draw <=", value, "isDraw");
            return (Criteria) this;
        }

        public Criteria andIsDrawIn(List<Integer> values) {
            addCriterion("is_draw in", values, "isDraw");
            return (Criteria) this;
        }

        public Criteria andIsDrawNotIn(List<Integer> values) {
            addCriterion("is_draw not in", values, "isDraw");
            return (Criteria) this;
        }

        public Criteria andIsDrawBetween(Integer value1, Integer value2) {
            addCriterion("is_draw between", value1, value2, "isDraw");
            return (Criteria) this;
        }

        public Criteria andIsDrawNotBetween(Integer value1, Integer value2) {
            addCriterion("is_draw not between", value1, value2, "isDraw");
            return (Criteria) this;
        }

        public Criteria andIsPrizeIsNull() {
            addCriterion("is_prize is null");
            return (Criteria) this;
        }

        public Criteria andIsPrizeIsNotNull() {
            addCriterion("is_prize is not null");
            return (Criteria) this;
        }

        public Criteria andIsPrizeEqualTo(Integer value) {
            addCriterion("is_prize =", value, "isPrize");
            return (Criteria) this;
        }

        public Criteria andIsPrizeNotEqualTo(Integer value) {
            addCriterion("is_prize <>", value, "isPrize");
            return (Criteria) this;
        }

        public Criteria andIsPrizeGreaterThan(Integer value) {
            addCriterion("is_prize >", value, "isPrize");
            return (Criteria) this;
        }

        public Criteria andIsPrizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_prize >=", value, "isPrize");
            return (Criteria) this;
        }

        public Criteria andIsPrizeLessThan(Integer value) {
            addCriterion("is_prize <", value, "isPrize");
            return (Criteria) this;
        }

        public Criteria andIsPrizeLessThanOrEqualTo(Integer value) {
            addCriterion("is_prize <=", value, "isPrize");
            return (Criteria) this;
        }

        public Criteria andIsPrizeIn(List<Integer> values) {
            addCriterion("is_prize in", values, "isPrize");
            return (Criteria) this;
        }

        public Criteria andIsPrizeNotIn(List<Integer> values) {
            addCriterion("is_prize not in", values, "isPrize");
            return (Criteria) this;
        }

        public Criteria andIsPrizeBetween(Integer value1, Integer value2) {
            addCriterion("is_prize between", value1, value2, "isPrize");
            return (Criteria) this;
        }

        public Criteria andIsPrizeNotBetween(Integer value1, Integer value2) {
            addCriterion("is_prize not between", value1, value2, "isPrize");
            return (Criteria) this;
        }

        public Criteria andIsFillMsgIsNull() {
            addCriterion("is_fill_msg is null");
            return (Criteria) this;
        }

        public Criteria andIsFillMsgIsNotNull() {
            addCriterion("is_fill_msg is not null");
            return (Criteria) this;
        }

        public Criteria andIsFillMsgEqualTo(Integer value) {
            addCriterion("is_fill_msg =", value, "isFillMsg");
            return (Criteria) this;
        }

        public Criteria andIsFillMsgNotEqualTo(Integer value) {
            addCriterion("is_fill_msg <>", value, "isFillMsg");
            return (Criteria) this;
        }

        public Criteria andIsFillMsgGreaterThan(Integer value) {
            addCriterion("is_fill_msg >", value, "isFillMsg");
            return (Criteria) this;
        }

        public Criteria andIsFillMsgGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_fill_msg >=", value, "isFillMsg");
            return (Criteria) this;
        }

        public Criteria andIsFillMsgLessThan(Integer value) {
            addCriterion("is_fill_msg <", value, "isFillMsg");
            return (Criteria) this;
        }

        public Criteria andIsFillMsgLessThanOrEqualTo(Integer value) {
            addCriterion("is_fill_msg <=", value, "isFillMsg");
            return (Criteria) this;
        }

        public Criteria andIsFillMsgIn(List<Integer> values) {
            addCriterion("is_fill_msg in", values, "isFillMsg");
            return (Criteria) this;
        }

        public Criteria andIsFillMsgNotIn(List<Integer> values) {
            addCriterion("is_fill_msg not in", values, "isFillMsg");
            return (Criteria) this;
        }

        public Criteria andIsFillMsgBetween(Integer value1, Integer value2) {
            addCriterion("is_fill_msg between", value1, value2, "isFillMsg");
            return (Criteria) this;
        }

        public Criteria andIsFillMsgNotBetween(Integer value1, Integer value2) {
            addCriterion("is_fill_msg not between", value1, value2, "isFillMsg");
            return (Criteria) this;
        }

        public Criteria andIsGetIsNull() {
            addCriterion("is_get is null");
            return (Criteria) this;
        }

        public Criteria andIsGetIsNotNull() {
            addCriterion("is_get is not null");
            return (Criteria) this;
        }

        public Criteria andIsGetEqualTo(Integer value) {
            addCriterion("is_get =", value, "isGet");
            return (Criteria) this;
        }

        public Criteria andIsGetNotEqualTo(Integer value) {
            addCriterion("is_get <>", value, "isGet");
            return (Criteria) this;
        }

        public Criteria andIsGetGreaterThan(Integer value) {
            addCriterion("is_get >", value, "isGet");
            return (Criteria) this;
        }

        public Criteria andIsGetGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_get >=", value, "isGet");
            return (Criteria) this;
        }

        public Criteria andIsGetLessThan(Integer value) {
            addCriterion("is_get <", value, "isGet");
            return (Criteria) this;
        }

        public Criteria andIsGetLessThanOrEqualTo(Integer value) {
            addCriterion("is_get <=", value, "isGet");
            return (Criteria) this;
        }

        public Criteria andIsGetIn(List<Integer> values) {
            addCriterion("is_get in", values, "isGet");
            return (Criteria) this;
        }

        public Criteria andIsGetNotIn(List<Integer> values) {
            addCriterion("is_get not in", values, "isGet");
            return (Criteria) this;
        }

        public Criteria andIsGetBetween(Integer value1, Integer value2) {
            addCriterion("is_get between", value1, value2, "isGet");
            return (Criteria) this;
        }

        public Criteria andIsGetNotBetween(Integer value1, Integer value2) {
            addCriterion("is_get not between", value1, value2, "isGet");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andIdentityNoIsNull() {
            addCriterion("identity_no is null");
            return (Criteria) this;
        }

        public Criteria andIdentityNoIsNotNull() {
            addCriterion("identity_no is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityNoEqualTo(String value) {
            addCriterion("identity_no =", value, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoNotEqualTo(String value) {
            addCriterion("identity_no <>", value, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoGreaterThan(String value) {
            addCriterion("identity_no >", value, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoGreaterThanOrEqualTo(String value) {
            addCriterion("identity_no >=", value, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoLessThan(String value) {
            addCriterion("identity_no <", value, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoLessThanOrEqualTo(String value) {
            addCriterion("identity_no <=", value, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoLike(String value) {
            addCriterion("identity_no like", value, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoNotLike(String value) {
            addCriterion("identity_no not like", value, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoIn(List<String> values) {
            addCriterion("identity_no in", values, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoNotIn(List<String> values) {
            addCriterion("identity_no not in", values, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoBetween(String value1, String value2) {
            addCriterion("identity_no between", value1, value2, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoNotBetween(String value1, String value2) {
            addCriterion("identity_no not between", value1, value2, "identityNo");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSizeIsNull() {
            addCriterion("size is null");
            return (Criteria) this;
        }

        public Criteria andSizeIsNotNull() {
            addCriterion("size is not null");
            return (Criteria) this;
        }

        public Criteria andSizeEqualTo(String value) {
            addCriterion("size =", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotEqualTo(String value) {
            addCriterion("size <>", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThan(String value) {
            addCriterion("size >", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThanOrEqualTo(String value) {
            addCriterion("size >=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThan(String value) {
            addCriterion("size <", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThanOrEqualTo(String value) {
            addCriterion("size <=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLike(String value) {
            addCriterion("size like", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotLike(String value) {
            addCriterion("size not like", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeIn(List<String> values) {
            addCriterion("size in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotIn(List<String> values) {
            addCriterion("size not in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeBetween(String value1, String value2) {
            addCriterion("size between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotBetween(String value1, String value2) {
            addCriterion("size not between", value1, value2, "size");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_game_status
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 14 15:34:55 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}