package com.clarks.pojo;

public class GameStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.user_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.first_pass
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer firstPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.first_join
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer firstJoin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.second_join
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer secondJoin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.first_best
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer firstBest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.second_pass
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer secondPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.second_best
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer secondBest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.is_scan
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer isScan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.is_draw
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer isDraw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.is_prize
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer isPrize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.is_fill_msg
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer isFillMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.is_get
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer isGet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.name
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.phone
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.address
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.identity_no
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String identityNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.sex
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_game_status.size
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.id
     *
     * @return the value of c_game_status.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.id
     *
     * @param id the value for c_game_status.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.user_id
     *
     * @return the value of c_game_status.user_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.user_id
     *
     * @param userId the value for c_game_status.user_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.first_pass
     *
     * @return the value of c_game_status.first_pass
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getFirstPass() {
        return firstPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.first_pass
     *
     * @param firstPass the value for c_game_status.first_pass
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setFirstPass(Integer firstPass) {
        this.firstPass = firstPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.first_join
     *
     * @return the value of c_game_status.first_join
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getFirstJoin() {
        return firstJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.first_join
     *
     * @param firstJoin the value for c_game_status.first_join
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setFirstJoin(Integer firstJoin) {
        this.firstJoin = firstJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.second_join
     *
     * @return the value of c_game_status.second_join
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getSecondJoin() {
        return secondJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.second_join
     *
     * @param secondJoin the value for c_game_status.second_join
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setSecondJoin(Integer secondJoin) {
        this.secondJoin = secondJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.first_best
     *
     * @return the value of c_game_status.first_best
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getFirstBest() {
        return firstBest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.first_best
     *
     * @param firstBest the value for c_game_status.first_best
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setFirstBest(Integer firstBest) {
        this.firstBest = firstBest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.second_pass
     *
     * @return the value of c_game_status.second_pass
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getSecondPass() {
        return secondPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.second_pass
     *
     * @param secondPass the value for c_game_status.second_pass
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setSecondPass(Integer secondPass) {
        this.secondPass = secondPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.second_best
     *
     * @return the value of c_game_status.second_best
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getSecondBest() {
        return secondBest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.second_best
     *
     * @param secondBest the value for c_game_status.second_best
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setSecondBest(Integer secondBest) {
        this.secondBest = secondBest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.is_scan
     *
     * @return the value of c_game_status.is_scan
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getIsScan() {
        return isScan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.is_scan
     *
     * @param isScan the value for c_game_status.is_scan
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setIsScan(Integer isScan) {
        this.isScan = isScan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.is_draw
     *
     * @return the value of c_game_status.is_draw
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getIsDraw() {
        return isDraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.is_draw
     *
     * @param isDraw the value for c_game_status.is_draw
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setIsDraw(Integer isDraw) {
        this.isDraw = isDraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.is_prize
     *
     * @return the value of c_game_status.is_prize
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getIsPrize() {
        return isPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.is_prize
     *
     * @param isPrize the value for c_game_status.is_prize
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setIsPrize(Integer isPrize) {
        this.isPrize = isPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.is_fill_msg
     *
     * @return the value of c_game_status.is_fill_msg
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getIsFillMsg() {
        return isFillMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.is_fill_msg
     *
     * @param isFillMsg the value for c_game_status.is_fill_msg
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setIsFillMsg(Integer isFillMsg) {
        this.isFillMsg = isFillMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.is_get
     *
     * @return the value of c_game_status.is_get
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getIsGet() {
        return isGet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.is_get
     *
     * @param isGet the value for c_game_status.is_get
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setIsGet(Integer isGet) {
        this.isGet = isGet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.name
     *
     * @return the value of c_game_status.name
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.name
     *
     * @param name the value for c_game_status.name
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.phone
     *
     * @return the value of c_game_status.phone
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.phone
     *
     * @param phone the value for c_game_status.phone
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.address
     *
     * @return the value of c_game_status.address
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.address
     *
     * @param address the value for c_game_status.address
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.identity_no
     *
     * @return the value of c_game_status.identity_no
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getIdentityNo() {
        return identityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.identity_no
     *
     * @param identityNo the value for c_game_status.identity_no
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setIdentityNo(String identityNo) {
        this.identityNo = identityNo == null ? null : identityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.sex
     *
     * @return the value of c_game_status.sex
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.sex
     *
     * @param sex the value for c_game_status.sex
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_game_status.size
     *
     * @return the value of c_game_status.size
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_game_status.size
     *
     * @param size the value for c_game_status.size
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }
}