package com.clarks.pojo;

import java.util.Date;

public class LoginRecord {
	
	
	public static final int LOGIN_SUCCESS = 1;
	public static final int LOGIN_FAILURE = 2;
	
	public static final int TYPE_ADMIN = 0;
	public static final int TYPE_USER = 1;
	
	public static final String LOGIN_SUCCESS_TITLE = "login success";
	public static final String LOGIN_FAILURE_TITLE = "login failure";
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_login_record.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_login_record.login_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Date loginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_login_record.user_name
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_login_record.login_ip
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_login_record.category
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_login_record.user_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_login_record.content
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_login_record.user_type
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_login_record.openId
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_login_record.username
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_login_record.id
     *
     * @return the value of c_login_record.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_login_record.id
     *
     * @param id the value for c_login_record.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_login_record.login_date
     *
     * @return the value of c_login_record.login_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Date getLoginDate() {
        return loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_login_record.login_date
     *
     * @param loginDate the value for c_login_record.login_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_login_record.user_name
     *
     * @return the value of c_login_record.user_name
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_login_record.user_name
     *
     * @param userName the value for c_login_record.user_name
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_login_record.login_ip
     *
     * @return the value of c_login_record.login_ip
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_login_record.login_ip
     *
     * @param loginIp the value for c_login_record.login_ip
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_login_record.category
     *
     * @return the value of c_login_record.category
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_login_record.category
     *
     * @param category the value for c_login_record.category
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_login_record.user_id
     *
     * @return the value of c_login_record.user_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_login_record.user_id
     *
     * @param userId the value for c_login_record.user_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_login_record.content
     *
     * @return the value of c_login_record.content
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_login_record.content
     *
     * @param content the value for c_login_record.content
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_login_record.user_type
     *
     * @return the value of c_login_record.user_type
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_login_record.user_type
     *
     * @param userType the value for c_login_record.user_type
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_login_record.openId
     *
     * @return the value of c_login_record.openId
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_login_record.openId
     *
     * @param openid the value for c_login_record.openId
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_login_record.username
     *
     * @return the value of c_login_record.username
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_login_record.username
     *
     * @param username the value for c_login_record.username
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}