package com.clarks.pojo;

import java.util.Date;

public class Prize {
	
	
	private String prizeNo;//优惠码
	private Integer isPrize;//是否中奖
	private Integer isGet;//是否领奖
	private Integer isFillMsg;//是否填写资料
	
	private Integer sendNum;//送出数量
	private Integer getNum;//领取数量
	
	

	
    public String getPrizeNo() {
		return prizeNo;
	}

	public void setPrizeNo(String prizeNo) {
		this.prizeNo = prizeNo;
	}

	public Integer getIsPrize() {
		return isPrize;
	}

	public void setIsPrize(Integer isPrize) {
		this.isPrize = isPrize;
	}

	public Integer getIsGet() {
		return isGet;
	}

	public void setIsGet(Integer isGet) {
		this.isGet = isGet;
	}

	public Integer getIsFillMsg() {
		return isFillMsg;
	}

	public void setIsFillMsg(Integer isFillMsg) {
		this.isFillMsg = isFillMsg;
	}

	public Integer getSendNum() {
		return sendNum;
	}

	public void setSendNum(Integer sendNum) {
		this.sendNum = sendNum;
	}

	public Integer getGetNum() {
		return getNum;
	}

	public void setGetNum(Integer getNum) {
		this.getNum = getNum;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize.prize_name
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String prizeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize.prize_desc
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String prizeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize.prize_pic
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String prizePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize.prize_prob
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Double prizeProb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize.day_limit
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer dayLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize.add_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Date addDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize.admin_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize.oper_user_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer operUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize.oper_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Date operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize.is_delete
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize.prize_level
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer prizeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize.all_num
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer allNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize.id
     *
     * @return the value of c_prize.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize.id
     *
     * @param id the value for c_prize.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize.prize_name
     *
     * @return the value of c_prize.prize_name
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getPrizeName() {
        return prizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize.prize_name
     *
     * @param prizeName the value for c_prize.prize_name
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setPrizeName(String prizeName) {
        this.prizeName = prizeName == null ? null : prizeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize.prize_desc
     *
     * @return the value of c_prize.prize_desc
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getPrizeDesc() {
        return prizeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize.prize_desc
     *
     * @param prizeDesc the value for c_prize.prize_desc
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setPrizeDesc(String prizeDesc) {
        this.prizeDesc = prizeDesc == null ? null : prizeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize.prize_pic
     *
     * @return the value of c_prize.prize_pic
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getPrizePic() {
        return prizePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize.prize_pic
     *
     * @param prizePic the value for c_prize.prize_pic
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setPrizePic(String prizePic) {
        this.prizePic = prizePic == null ? null : prizePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize.prize_prob
     *
     * @return the value of c_prize.prize_prob
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Double getPrizeProb() {
        return prizeProb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize.prize_prob
     *
     * @param prizeProb the value for c_prize.prize_prob
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setPrizeProb(Double prizeProb) {
        this.prizeProb = prizeProb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize.day_limit
     *
     * @return the value of c_prize.day_limit
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getDayLimit() {
        return dayLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize.day_limit
     *
     * @param dayLimit the value for c_prize.day_limit
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setDayLimit(Integer dayLimit) {
        this.dayLimit = dayLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize.add_date
     *
     * @return the value of c_prize.add_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize.add_date
     *
     * @param addDate the value for c_prize.add_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize.admin_id
     *
     * @return the value of c_prize.admin_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize.admin_id
     *
     * @param adminId the value for c_prize.admin_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize.oper_user_id
     *
     * @return the value of c_prize.oper_user_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getOperUserId() {
        return operUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize.oper_user_id
     *
     * @param operUserId the value for c_prize.oper_user_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setOperUserId(Integer operUserId) {
        this.operUserId = operUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize.oper_date
     *
     * @return the value of c_prize.oper_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Date getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize.oper_date
     *
     * @param operDate the value for c_prize.oper_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setOperDate(Date operDate) {
        this.operDate = operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize.is_delete
     *
     * @return the value of c_prize.is_delete
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize.is_delete
     *
     * @param isDelete the value for c_prize.is_delete
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize.prize_level
     *
     * @return the value of c_prize.prize_level
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getPrizeLevel() {
        return prizeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize.prize_level
     *
     * @param prizeLevel the value for c_prize.prize_level
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setPrizeLevel(Integer prizeLevel) {
        this.prizeLevel = prizeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize.all_num
     *
     * @return the value of c_prize.all_num
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getAllNum() {
        return allNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize.all_num
     *
     * @param allNum the value for c_prize.all_num
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setAllNum(Integer allNum) {
        this.allNum = allNum;
    }
}