package com.clarks.pojo;

import java.util.Date;

public class PrizeRecord {
	
	private User user;
	private Prize prize;
	
    public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Prize getPrize() {
		return prize;
	}

	public void setPrize(Prize prize) {
		this.prize = prize;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize_record.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize_record.prize_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer prizeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize_record.user_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize_record.is_get
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer isGet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize_record.date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_prize_record.prize_no
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String prizeNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize_record.id
     *
     * @return the value of c_prize_record.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize_record.id
     *
     * @param id the value for c_prize_record.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize_record.prize_id
     *
     * @return the value of c_prize_record.prize_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getPrizeId() {
        return prizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize_record.prize_id
     *
     * @param prizeId the value for c_prize_record.prize_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setPrizeId(Integer prizeId) {
        this.prizeId = prizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize_record.user_id
     *
     * @return the value of c_prize_record.user_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize_record.user_id
     *
     * @param userId the value for c_prize_record.user_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize_record.is_get
     *
     * @return the value of c_prize_record.is_get
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getIsGet() {
        return isGet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize_record.is_get
     *
     * @param isGet the value for c_prize_record.is_get
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setIsGet(Integer isGet) {
        this.isGet = isGet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize_record.date
     *
     * @return the value of c_prize_record.date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize_record.date
     *
     * @param date the value for c_prize_record.date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_prize_record.prize_no
     *
     * @return the value of c_prize_record.prize_no
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getPrizeNo() {
        return prizeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_prize_record.prize_no
     *
     * @param prizeNo the value for c_prize_record.prize_no
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setPrizeNo(String prizeNo) {
        this.prizeNo = prizeNo == null ? null : prizeNo.trim();
    }
}