package com.clarks.pojo;

import java.util.Date;

public class Statistic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_statistic.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_statistic.session_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_statistic.ip
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_statistic.page_url
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String pageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_statistic.request_url
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String requestUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_statistic.add_time
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_statistic.username
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_statistic.day_register_sum
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer dayRegisterSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_statistic.day_draw_sum
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer dayDrawSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_statistic.statistic_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Date statisticDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_statistic.day_pv
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer dayPv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_statistic.day_uv
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    private Integer dayUv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_statistic.id
     *
     * @return the value of c_statistic.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_statistic.id
     *
     * @param id the value for c_statistic.id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_statistic.session_id
     *
     * @return the value of c_statistic.session_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_statistic.session_id
     *
     * @param sessionId the value for c_statistic.session_id
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_statistic.ip
     *
     * @return the value of c_statistic.ip
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_statistic.ip
     *
     * @param ip the value for c_statistic.ip
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_statistic.page_url
     *
     * @return the value of c_statistic.page_url
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getPageUrl() {
        return pageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_statistic.page_url
     *
     * @param pageUrl the value for c_statistic.page_url
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl == null ? null : pageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_statistic.request_url
     *
     * @return the value of c_statistic.request_url
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getRequestUrl() {
        return requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_statistic.request_url
     *
     * @param requestUrl the value for c_statistic.request_url
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl == null ? null : requestUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_statistic.add_time
     *
     * @return the value of c_statistic.add_time
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_statistic.add_time
     *
     * @param addTime the value for c_statistic.add_time
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_statistic.username
     *
     * @return the value of c_statistic.username
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_statistic.username
     *
     * @param username the value for c_statistic.username
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_statistic.day_register_sum
     *
     * @return the value of c_statistic.day_register_sum
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getDayRegisterSum() {
        return dayRegisterSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_statistic.day_register_sum
     *
     * @param dayRegisterSum the value for c_statistic.day_register_sum
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setDayRegisterSum(Integer dayRegisterSum) {
        this.dayRegisterSum = dayRegisterSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_statistic.day_draw_sum
     *
     * @return the value of c_statistic.day_draw_sum
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getDayDrawSum() {
        return dayDrawSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_statistic.day_draw_sum
     *
     * @param dayDrawSum the value for c_statistic.day_draw_sum
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setDayDrawSum(Integer dayDrawSum) {
        this.dayDrawSum = dayDrawSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_statistic.statistic_date
     *
     * @return the value of c_statistic.statistic_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Date getStatisticDate() {
        return statisticDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_statistic.statistic_date
     *
     * @param statisticDate the value for c_statistic.statistic_date
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setStatisticDate(Date statisticDate) {
        this.statisticDate = statisticDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_statistic.day_pv
     *
     * @return the value of c_statistic.day_pv
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getDayPv() {
        return dayPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_statistic.day_pv
     *
     * @param dayPv the value for c_statistic.day_pv
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setDayPv(Integer dayPv) {
        this.dayPv = dayPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_statistic.day_uv
     *
     * @return the value of c_statistic.day_uv
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public Integer getDayUv() {
        return dayUv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_statistic.day_uv
     *
     * @param dayUv the value for c_statistic.day_uv
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    public void setDayUv(Integer dayUv) {
        this.dayUv = dayUv;
    }
}