package com.clarks.pojo;

import java.util.Date;

public class User {
	
// 统计数据
	private Long userNum;
	private Long firstJoin;
	private Long firstPass;
	private Long secondJoin;
	private Long secondPass;
	private Long drawNum;


	
	public void initForRegister() {
		this.setDrawNum(0L);
		this.setStatus(0);
		this.setLoginTimes(0);
	}
	
	public User(){
		
	}

	public User(String username, String password, String nickName) {
		
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.id
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.username
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.password
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.nick_name
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.open_id
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.headPic
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private String headpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.register_time
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.first_login_time
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private Date firstLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.last_login_time
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.status
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.login_times
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private Integer loginTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.sex
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private Integer sex;

  

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.id
     *
     * @return the value of c_user.id
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.id
     *
     * @param id the value for c_user.id
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.username
     *
     * @return the value of c_user.username
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.username
     *
     * @param username the value for c_user.username
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.password
     *
     * @return the value of c_user.password
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.password
     *
     * @param password the value for c_user.password
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.nick_name
     *
     * @return the value of c_user.nick_name
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.nick_name
     *
     * @param nickName the value for c_user.nick_name
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.open_id
     *
     * @return the value of c_user.open_id
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.open_id
     *
     * @param openId the value for c_user.open_id
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.headPic
     *
     * @return the value of c_user.headPic
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public String getHeadpic() {
        return headpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.headPic
     *
     * @param headpic the value for c_user.headPic
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setHeadpic(String headpic) {
        this.headpic = headpic == null ? null : headpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.register_time
     *
     * @return the value of c_user.register_time
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.register_time
     *
     * @param registerTime the value for c_user.register_time
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.first_login_time
     *
     * @return the value of c_user.first_login_time
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public Date getFirstLoginTime() {
        return firstLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.first_login_time
     *
     * @param firstLoginTime the value for c_user.first_login_time
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setFirstLoginTime(Date firstLoginTime) {
        this.firstLoginTime = firstLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.last_login_time
     *
     * @return the value of c_user.last_login_time
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.last_login_time
     *
     * @param lastLoginTime the value for c_user.last_login_time
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.status
     *
     * @return the value of c_user.status
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.status
     *
     * @param status the value for c_user.status
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.login_times
     *
     * @return the value of c_user.login_times
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public Integer getLoginTimes() {
        return loginTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.login_times
     *
     * @param loginTimes the value for c_user.login_times
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setLoginTimes(Integer loginTimes) {
        this.loginTimes = loginTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.sex
     *
     * @return the value of c_user.sex
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.sex
     *
     * @param sex the value for c_user.sex
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }


	public Long getUserNum() {
		return userNum;
	}


	public void setUserNum(Long userNum) {
		this.userNum = userNum;
	}


	public Long getFirstJoin() {
		return firstJoin;
	}


	public void setFirstJoin(Long firstJoin) {
		this.firstJoin = firstJoin;
	}


	public Long getFirstPass() {
		return firstPass;
	}


	public void setFirstPass(Long firstPass) {
		this.firstPass = firstPass;
	}


	public Long getSecondJoin() {
		return secondJoin;
	}


	public void setSecondJoin(Long secondJoin) {
		this.secondJoin = secondJoin;
	}


	public Long getSecondPass() {
		return secondPass;
	}


	public void setSecondPass(Long secondPass) {
		this.secondPass = secondPass;
	}


	public Long getDrawNum() {
		return drawNum;
	}


	public void setDrawNum(Long drawNum) {
		this.drawNum = drawNum;
	}
    
    
}