package com.clarks.pojo;

import java.util.Date;

public class WxAuthorize {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wx_authorize.id
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wx_authorize.open_id
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wx_authorize.access_token
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wx_authorize.refresh_token
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private String refreshToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wx_authorize.expires_in
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private Integer expiresIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wx_authorize.update_date
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_wx_authorize.user_id
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wx_authorize.id
     *
     * @return the value of c_wx_authorize.id
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wx_authorize.id
     *
     * @param id the value for c_wx_authorize.id
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wx_authorize.open_id
     *
     * @return the value of c_wx_authorize.open_id
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wx_authorize.open_id
     *
     * @param openId the value for c_wx_authorize.open_id
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wx_authorize.access_token
     *
     * @return the value of c_wx_authorize.access_token
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wx_authorize.access_token
     *
     * @param accessToken the value for c_wx_authorize.access_token
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wx_authorize.refresh_token
     *
     * @return the value of c_wx_authorize.refresh_token
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wx_authorize.refresh_token
     *
     * @param refreshToken the value for c_wx_authorize.refresh_token
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken == null ? null : refreshToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wx_authorize.expires_in
     *
     * @return the value of c_wx_authorize.expires_in
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public Integer getExpiresIn() {
        return expiresIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wx_authorize.expires_in
     *
     * @param expiresIn the value for c_wx_authorize.expires_in
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setExpiresIn(Integer expiresIn) {
        this.expiresIn = expiresIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wx_authorize.update_date
     *
     * @return the value of c_wx_authorize.update_date
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wx_authorize.update_date
     *
     * @param updateDate the value for c_wx_authorize.update_date
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wx_authorize.user_id
     *
     * @return the value of c_wx_authorize.user_id
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wx_authorize.user_id
     *
     * @param userId the value for c_wx_authorize.user_id
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}