Server:
  port: 80
  servlet:
    context-path: /clarks

spring:
#  mvc:
#    view:
#      suffix: .jsp
#      prefix: /WEB-INF/jsp/
  datasource:
    url: jdbc:mysql://localhost:3306/clarks?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: 494727043
    driver-class-name: com.mysql.cj.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 验证不同类型数据库的有效性
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
#    filters: commons-log.connection-logger-name: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
#    useGlobalDataSourceStat: true

#  redis:
#    # 索引默认为0
#    database: 1
#    # 服务器地址
#    host: 192.168.1.23
#    # 端口
#    port: 6379
#    # 服务器链接密码
#    password:
#    # 连接超时（毫秒）
#    timeout: 0
#    jedis:
#      # 连接池
#      pool:
#        # 最大连接数
#        max-active: 1000
#        # 最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#        # 最大空闲链接
#        max-idle: 10
#        # 最小空闲链接
#        min-idle: 2




mybatis:
    # 设置实体类包
    type-aliases-package: com.clarks.pojo
    # 设置Mapper.xml文件
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.clarks.mybatisutils.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql




