Server:
  port: 80
  servlet:
    context-path: /spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clarks-boot
    username: root
    password: 494727043
    driver-class-name: com.mysql.cj.jdbc.Driver
p:
  name: kkk
  age:  28