package com.clarks.mapper;

import com.clarks.pojo.Config;
import com.clarks.pojo.ConfigExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface ConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int countByExample(ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int deleteByExample(ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int insert(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int insertSelective(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    List<Config> selectByExample(ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    Config selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") Config record, @Param("example") ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByExample(@Param("record") Config record, @Param("example") ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByPrimaryKeySelective(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_config
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByPrimaryKey(Config record);
}