package com.clarks.mapper;

import com.clarks.pojo.DailyCount;
import com.clarks.pojo.DailyCountExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.List;
@Component
public interface DailyCountMapper {
	//去重查询当天登录次数
	int selectDailCount(@Param("date") Date date, @Param("nowTime") Date nowTime);
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_daily_count
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int countByExample(DailyCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_daily_count
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int deleteByExample(DailyCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_daily_count
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_daily_count
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int insert(DailyCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_daily_count
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int insertSelective(DailyCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_daily_count
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    List<DailyCount> selectByExample(DailyCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_daily_count
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    DailyCount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_daily_count
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") DailyCount record, @Param("example") DailyCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_daily_count
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByExample(@Param("record") DailyCount record, @Param("example") DailyCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_daily_count
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByPrimaryKeySelective(DailyCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_daily_count
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByPrimaryKey(DailyCount record);
}