package com.clarks.mapper;

import com.clarks.pojo.File;
import com.clarks.pojo.FileExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_front_file
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int countByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_front_file
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int deleteByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_front_file
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_front_file
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_front_file
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int insertSelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_front_file
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    List<File> selectByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_front_file
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    File selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_front_file
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") File record, @Param("example") FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_front_file
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByExample(@Param("record") File record, @Param("example") FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_front_file
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByPrimaryKeySelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_front_file
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByPrimaryKey(File record);
}