package com.clarks.mapper;

import com.clarks.pojo.GameStatus;
import com.clarks.pojo.GameStatusExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface GameStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int countByExample(GameStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int deleteByExample(GameStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int insert(GameStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int insertSelective(GameStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    List<GameStatus> selectByExample(GameStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    GameStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") GameStatus record, @Param("example") GameStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByExample(@Param("record") GameStatus record, @Param("example") GameStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByPrimaryKeySelective(GameStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_game_status
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByPrimaryKey(GameStatus record);
}