package com.clarks.mapper;

import com.clarks.pojo.Prize;
import com.clarks.pojo.PrizeExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface PrizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_prize
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int countByExample(PrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_prize
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int deleteByExample(PrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_prize
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_prize
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int insert(Prize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_prize
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int insertSelective(Prize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_prize
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    List<Prize> selectByExample(PrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_prize
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    Prize selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_prize
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") Prize record, @Param("example") PrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_prize
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByExample(@Param("record") Prize record, @Param("example") PrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_prize
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByPrimaryKeySelective(Prize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_prize
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByPrimaryKey(Prize record);
}