package com.clarks.mapper;

import com.clarks.pojo.Statistic;
import com.clarks.pojo.StatisticExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface StatisticMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_statistic
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int countByExample(StatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_statistic
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int deleteByExample(StatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_statistic
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_statistic
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int insert(Statistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_statistic
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int insertSelective(Statistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_statistic
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    List<Statistic> selectByExample(StatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_statistic
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    Statistic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_statistic
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") Statistic record, @Param("example") StatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_statistic
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByExample(@Param("record") Statistic record, @Param("example") StatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_statistic
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByPrimaryKeySelective(Statistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_statistic
     *
     * @mbggenerated Tue Aug 14 15:34:55 CST 2018
     */
    int updateByPrimaryKey(Statistic record);
}