package com.clarks.mapper;

import com.clarks.pojo.WxAuthorize;
import com.clarks.pojo.WxAuthorizeExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface WxAuthorizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wx_authorize
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    int countByExample(WxAuthorizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wx_authorize
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    int deleteByExample(WxAuthorizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wx_authorize
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wx_authorize
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    int insert(WxAuthorize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wx_authorize
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    int insertSelective(WxAuthorize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wx_authorize
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    List<WxAuthorize> selectByExample(WxAuthorizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wx_authorize
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    WxAuthorize selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wx_authorize
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxAuthorize record, @Param("example") WxAuthorizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wx_authorize
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    int updateByExample(@Param("record") WxAuthorize record, @Param("example") WxAuthorizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wx_authorize
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    int updateByPrimaryKeySelective(WxAuthorize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wx_authorize
     *
     * @mbggenerated Tue Aug 14 15:34:56 CST 2018
     */
    int updateByPrimaryKey(WxAuthorize record);
}